databases:
  - name: recipient
    databaseName: recipient

services:
  - type: web
    name: recipient-ori
    env: ruby
    buildCommand: "./bin/recipes-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipient
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false